# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

worstcase_l1 <- function(z, q, t) {
    .Call(`_rcraam_worstcase_l1`, z, q, t)
}

solve_mdp <- function(mdp, discount, algorithm) {
    .Call(`_rcraam_solve_mdp`, mdp, discount, algorithm)
}

