# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

worstcase_l1 <- function(z, q, t) {
    .Call(`_rcraam_worstcase_l1`, z, q, t)
}

example_mdp <- function(name) {
    .Call(`_rcraam_example_mdp`, name)
}

pack_actions <- function(mdp) {
    .Call(`_rcraam_pack_actions`, mdp)
}

solve_mdp <- function(mdp, discount, options) {
    .Call(`_rcraam_solve_mdp`, mdp, discount, options)
}

rsolve_mdp_sa <- function(mdp, discount, nature, nature_par, options) {
    .Call(`_rcraam_rsolve_mdp_sa`, mdp, discount, nature, nature_par, options)
}

rsolve_mdp_s <- function(mdp, discount, nature, nature_par, options) {
    .Call(`_rcraam_rsolve_mdp_s`, mdp, discount, nature, nature_par, options)
}

